- name: install depds block
  block:

    - name: Install some packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - socat 
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install epel-release
      package:
        state: latest
        name: epel-release
      when: ansible_distribution == 'CentOS'

    - name: Install some packages
      package:
        name: "{{ packages }}"
      vars:
        packages:
          - socat
      when: ansible_distribution == 'CentOS'

  when:
    - install_system_deps|default(true)|bool

- name: add user to run haproxy as
  user:
    name: "{{ haproxy_username }}"
    shell: /sbin/nologin
    createhome: no
    home: "{{ haproxy_dir }}"
  tags:
    - haproxy_user
