- set_fact:
    server_arch: >-
      {%- if ansible_architecture in ["armv7l", "armhf", "aarch32"] -%}
      armhf
      {%- elif ansible_architecture in ["armv8l", "aarch64"] -%}
      arm64
      {%- elif ansible_architecture == "x86_64" -%}
      amd64
      {%- endif -%}
  tags: always

- set_fact:
    certbot_tag: "{{ certbot_tag_arch_map[server_arch] }}"
  tags: always

- import_tasks: install.yml
  tags:
    - haproxy_install

- import_tasks: certbot.yml
  tags:
    - certbot_install

- import_tasks: firewalld.yml
  tags:
    - haproxy_firewalld
  when:
    - ansible_distribution == 'CentOS'
    - configure_firewall|default(false)|bool

- import_tasks: ufw.yml
  tags:
    - haproxy_ufw
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - configure_firewall|default(false)|bool

- import_tasks: haproxy.yml
  tags:
    - haproxy_config

- import_tasks: uninstall.yml
  tags:
    - uninstall
    - uninstall_loadbalancer
  when: uninstall_playbook is defined and uninstall_playbook|bool == True
