- name: allow remote lb ports in firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ item }}"
  with_items:
    - "{{ node_api_port_remote }}"
    - "{{ haproxy_stats_port }}"

- name: Set ufw logging
  ufw:
    logging: "{{ ufw_logging }}"

- name: rate limit node api port in firewall
  ufw:
    rule: limit
    direction: in
    proto: tcp
    port: "{{ node_api_port_remote }}"
    log: yes
  when:
    - ufw_limit_node_api | default(false) | bool

- name: allow haporxy peering port in firewall
  ufw:
    rule: allow
    direction: in
    src: "{{ item[0] }}"
    proto: "{{ item[1].proto }}"
    port: "{{ item[1].port }}"
  with_nested:
    - "{{ groups['fullnode'] | map('extract', hostvars, ['ip']) | list | difference([ip]) }}"
    - - {"port": '{{ haproxy_peer_port }}', "proto": "tcp"}
  when: groups['fullnode'] | length > 1
